[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python -m uvicorn app:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 75 --workers 1"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckInterval = 45

[variables]
PYTHON_VERSION = "3.13.0"