[build]
builder = "dockerfile"
buildCommand = "docker build -t app ."

[deploy]
startCommand = "docker run -p ${PORT}:${PORT} -e PORT=${PORT} app"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckInterval = 45

[variables]
PYTHON_VERSION = "3.13.0"