[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.prod.txt"
watchPatterns = ["requirements.prod.txt"]

[phases.setup]
nixPkgs = ["python3"]
cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.prod.txt"]

[deploy]
startCommand = "cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100

[variables]
PYTHON_VERSION = "3.13.0"