[project]
name = "chainwatch-api"
version = "0.1.0"
description = "ChainWatch API"
requires-python = ">=3.11,<3.12"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["index"]